### ISSUE TITLE
No page reload after skipWaiting 

### ISSUE THREAD

**Issue by madeInLagny** [thepassle/pwa-helpers#16]
Thanks for this great plug-in
I have a open-wc application. I have added your plug-in to handle sw updates.

Here is how it looks like
`import { addPwaUpdateListener } from 'pwa-helper-components';`

```
constructor() {
    super();
    this.updateAvailable = false;
  }
```
```

connectedCallback() {
    super.connectedCallback();
    addPwaUpdateListener(updateAvailable => {
      this.updateAvailable = updateAvailable;
    });
  }

```
When truthy, this.updateAvailable shows a panel that has a 'install update' button. Button click method is as follows:

```
<button
@click=${() => this.skipWaiting()}>
Install update
</button>

```
```

async skipWaiting() {
    const reg = await navigator.serviceWorker.getRegistration();
    reg.waiting.postMessage({ type: 'SKIP_WAITING' });
  }

```
When button is clicked, the method is called and reg is loaded (checked in console) no error is thrown but nothing happens and the page never reloads. Any idea ?

here is my rollup.config.js

```
import merge from 'deepmerge';
import { createSpaConfig } from '@open-wc/building-rollup';
import copy from 'rollup-plugin-copy';
import replace from '@rollup/plugin-replace';
import dynamicImportVars from '@rollup/plugin-dynamic-import-vars';

const baseConfig = createSpaConfig({
  developmentMode: process.env.ROLLUP_WATCH === 'true',

  workbox: {
    skipWaiting: false,
    clientsClaim: false,
  },
  injectServiceWorker: true,
});

export default merge(baseConfig, {
  input: './index.html',

  plugins: [
    replace({
      ___appNamePrefix___: 'autoScrib_',
      ___appName___: 'autoScrib',
      __dev__: 'prod',
      __color1__: '#314d8a',
      delimiters: ['', ''],
    }),
    dynamicImportVars({
      exclude: 'views/template-page/template-page.js',
    }),
    copy({
      targets: [
        {
          src: 'assets/**/*.jpg',
          dest: 'dist/assets',
        },
        {
          src: 'assets/**/*.png',
          dest: 'dist/assets',
        },
        {
          src: 'manifests',
          dest: 'dist',
        },
      ],
      hook: 'buildStart',
      flatten: false,
    }),
  ],
});

```

**Comment by thepassle** [comment]
Can you confirm that it does in fact skip waiting, and the new service worker has taken over?

As for refreshing, thats functionality you'll have to implement yourself when the `controllerchange` event has fired (which means the new service worker has skipped waiting and taken over), you can see an example of that here:

https://github.com/thepassle/pwa-helpers/blob/master/pwa-update-available/PwaUpdateAvailable.js#L33

**Comment by madeInLagny** [comment]
Thanks ! I have implemented the controler listener, and the page does
refresh now. How can I check that the sw skips waiting ?

Le sam. 2 janv. 2021 à 15:58, Pascal Schilp <notifications@github.com> a
écrit :

**Comment by thepassle** [comment]
If the page refreshes that means the `controllerchange` event has fired, and also that the service worker has skipped waiting 🙁

**Comment by madeInLagny** [comment]
Perfect then. Thanks for your support

Le sam. 2 janv. 2021 à 16:21, Pascal Schilp <notifications@github.com> a
écrit :
