### ISSUE TITLE
PwaUpdateAvailable does not work with open-wc service worker

### ISSUE THREAD

**Issue by lpellegr** [thepassle/pwa-helpers#2]
I gave a quick try to your PwaUpdateAvailable component in combination with an [open-wc](https://open-wc.org/) managed app that uses the new service worker implementation you made. 

The service worker that is generated is working great and your button is displayed on an update. However, when I click on the update button nothing is happening (i.e. the new service worker is not activated and as a consequence, the page is not reloaded). 

After investigating, I noticed the service worker defines a message listener as follows:

```javascript
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
```

However, your component implementation post the following message:

```javascript
this._newWorker.postMessage('skipWaiting');
```

I made a quick test by changing your compoment message payload to:

```javascript
this._newWorker.postMessage({type: 'SKIP_WAITING'});
```

This fixed the issue.

**Comment by thepassle** [comment]
Thats a really good point, thanks for pointing that out! Would you be willing to make a PR? :)
